services:
  - type: web
    name: bus-tracking-backend
    env: java
    plan: free
    region: oregon
    rootDir: Backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
